# Generated by Django 4.2.2 on 2023-06-26 11:39

import Post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to=Post.models.nameFile),
        ),
    ]
